### ISSUE TITLE
PLD AF Possible texture issue

### ISSUE THREAD

**Issue by andre-macc** [Ashenbubs/AshenbubsHD-Beta#2]
Not sure if this is a problem or not. Thought I'd report it.

![image](https://user-images.githubusercontent.com/72416751/102573385-1d5c6580-40cd-11eb-91af-a1cdcfe5d726.png)

**Comment by Ashenbubs** [comment]
This is on PLD AF1 and AF2 - Any armor that uses this model, but I think this is the only one - Mithrans and Female Humes share the same armor for the most part (albeit Mithrans tend to remove some pieces... But they have the same body shape), and this is also happening on Hume Females.

In short, I think it's just an issue with how the texture is applied to the model itself, as no other race/genders have this issue on the armor, sadly!

I'd be interested to see what the original armor looks like actually... I'll have to load a backup and take a look - But this might have been a workaround SE did to cover something up, which is a shame because I think it might have just been a mistake as no other armor looks to have this issue, and I wouldn't know how to go around editing the model itself to resolve this :/
